version: '3'
services:
  db:
    container_name: restaurant_db
    build:
      context: db
      dockerfile: Dockerfile
  app:
    container_name: restaurant_app
    build:
      context: app
      dockerfile: Dockerfile
    links:
      - db
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: restaurant_server
    links:
      - app
    ports:
      - '80:80'
