# restaurantes/urls.py

from django.conf.urls import url, include
from . import views

# add for rest #
from rest_framework_mongoengine import routers
from . import serializers

# this is DRF router for REST API viewsets
router = routers.DefaultRouter()

# register REST API endpoints with DRF router
router.register(r'restaurants', serializers.restaurantsViewSet, r"restaurants")
# end add #

urlpatterns = [

  url(r'^$', views.index, name='index'), # init page
  url(r'^test/$', views.test, name='test'),
  url(r'^buscar/$', views.buscar, name='buscar'), # search by cuisine
  url(r'^listar/$', views.listar, name='listar'), # list items
  url(r'^add/$', views.add, name='add'), # add item
  url(r'^restaurant/(?P<name>.+)$', views.restaurant, name='restaurant'), # item details
  url(r'^imagen/(?P<name>.+)$', views.imagen, name='imagen'), # show image item
  url(r'^r_ajax/(?P<name>.+)$', views.r_ajax, name='r_ajax'), # JQuery Ajax
  url(r'^api/', include(router.urls, namespace='api')), # REST API root view (generated by DRF router)
]
